### ISSUE TITLE
Kotlin Language Client client: couldn't create connection to server.

### ISSUE THREAD

**Issue by Emandac** [fwcd/vscode-kotlin#158]
every time i open a file ending .kt this bug happened to me 
it was working just fine a day a go
maybe because of a vscode update but idk

version JDK: java 17.0.12 2024-07-16 LTS

version of kotlin: 2.0.0-release-341 (JRE 17.0.12+8-LTS-286)

version extenstion : 0.2.35

Error message:
[Error - 9:46:46 PM] Kotlin Language Client client: couldn't create connection to server.
Error: spawn EINVAL
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:799:9)
	at c:\Users\accompagnant\.vscode\extensions\fwcd.kotlin-0.2.35\dist\extension.js:2:763567
	at async k.createConnection (c:\Users\accompagnant\.vscode\extensions\fwcd.kotlin-0.2.35\dist\extension.js:2:602530)
	at async k.start (c:\Users\accompagnant\.vscode\extensions\fwcd.kotlin-0.2.35\dist\extension.js:2:593505)
![Screenshot (1584)](https://github.com/user-attachments/assets/ad29514b-f650-43a8-bd7c-3d9d387a3886)
![Screenshot (1585)](https://github.com/user-attachments/assets/e588e741-85ca-468d-8507-e2ddb6cdf214)

**Comment by SaintFTS** [comment]
i have the same problem, any solution?

**Comment by othercorey** [comment]
I think this started happening for me the July 2024 (1.92) vscode update.

**Comment by willnode** [comment]
This is could be because of https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2 exactly in 
https://github.com/fwcd/vscode-kotlin/blob/a2b912de4fa9139eacd976bc0b22907105b83e4a/src/languageSetup.ts#L250

**Comment by othercorey** [comment]
@fwcd Looks like the vscode team opened an issue about this change:

https://github.com/fwcd/vscode-kotlin/issues/153

**Comment by projectGuy7** [comment]
> This is could be because of https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2 exactly in
> 
> https://github.com/fwcd/vscode-kotlin/blob/a2b912de4fa9139eacd976bc0b22907105b83e4a/src/languageSetup.ts#L250

Is that languageSetup.ts located in extension's source code?
If I understand right, we need to add "shell : true" to that method, so it works correctly, but I have a huge trouble with finding that file

**Comment by onixldlc** [comment]
im not saying editing the extension file is impossible... but i think it would be easier to just fork it or find a fork with the fix then copy the js file from the build to your extension folder since the js is jumbbled, altho if you are stubborn enough like me or cant wait and want to change it now... you can do it too, like this:

if you are in windows you can go to (in linux its probably ~/.vscode but cmiiw)

%USERPROFILE%\.vscode\extensions\fwcd.kotlin-0.2.35\dist

then look for
``` 
,["--tcpClientPort",t]
// change it to
,["--tcpClientPort",t],{shell:true}
```

![image](https://github.com/user-attachments/assets/d1c0865b-fa5a-47f5-8b06-3ad948a19070)

but not only this you will have to add `c.shell=true where ` where ever you found `.spawn(` like so
![image](https://github.com/user-attachments/assets/4cbd52ba-168f-4dc9-b1fd-c14f71723a08)
and i would suggest using any lightweight text editor like vim nano or notepad (i tried using vscode and it lagged pretty hard for every letter i pressed, tbf i had js extension so maybe disable it ? idk didnt try)

**Comment by alirezaArz** [comment]
i have the same problem for 2 days

**Comment by alirezaArz** [comment]
i have the same problem for 2 days

**Comment by A-Boring-Square** [comment]
Here is the patched file
[PATCH.zip](https://github.com/user-attachments/files/16682790/PATCH.zip)

**Comment by Emandac** [comment]
> Here is the patched file [PATCH.zip](https://github.com/user-attachments/files/16682790/PATCH.zip)

Where do I put the extracted files ?

**Comment by A-Boring-Square** [comment]
%USERPROFILE%\.vscode\extensions\fwcd.kotlin-0.2.35\dist this will replace the js file

**Comment by Emandac** [comment]
> %USERPROFILE%.vscode\extensions\fwcd.kotlin-0.2.35\dist this will replace the js file

Thank 😊

**Comment by RowdyRushya** [comment]
@A-Boring-Square  You are the real GOAT

**Comment by A-Boring-Square** [comment]
Your welcome what's funny is I don't even use this extension anymore

**Comment by halotroop2288** [comment]
> Here is the patched file [PATCH.zip](https://github.com/user-attachments/files/16682790/PATCH.zip)

Why not make a pull request and link it here if you know how to fix it?

**Comment by willnode** [comment]
@fwcd should already fixes it then

**Comment by TheErondu** [comment]
The patch still works just added it today and it fixed it ...
Any plans for @fwcd to include a fix in the main?

**Comment by othercorey** [comment]
I don't think the repo owner checks issues.

**Comment by TheErondu** [comment]
> I don't think the repo owner checks issues.

what do we do then?

**Comment by onixldlc** [comment]
![image](https://github.com/user-attachments/assets/4daf105e-79cc-4745-9166-a534aebad9be)
im not sure what you mean by "null" when trying to hover ? or is it me using the older version of vscode ? 

this is my vscode about section:
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Electron: 32.2.1
ElectronBuildId: 10427718
Node.js: 20.18.0
V8: 12.8.374.38-electron.0

**Comment by EDM115** [comment]
@onixldlc thanks for [your tips](https://github.com/fwcd/vscode-kotlin/issues/158#issuecomment-2290720525) :)  
since you seem to understand what to edit, what do we need to change there in the dist for spawned processes to work on paths where there's spaces. for example this will always be the case on VS Code Insiders, as the cached data (language server) is in `%APPDATA%\Code - Insiders\User\globalStorage\fwcd.kotlin`

**Comment by EDM115** [comment]
anyway i fixed it
here's the dist files, and the vsix if you're lazy :  
[dist.zip](https://github.com/user-attachments/files/17899868/dist.zip)  
[kotlin-0.3.0-vsix.zip](https://github.com/user-attachments/files/17899874/kotlin-0.3.0-vsix.zip)

**Comment by EDM115** [comment]
@fwcd it's really nice that you fixed the issue, however note that the extension still won't work when the path to the language server contains spaces (ex when using VS Code Insiders)  
perhaps check what I did [here](https://github.com/EDM115/vscode-kotlin/commit/a63745c5d9c8baefa363d9b72870d289708a7a74), I don't know if it's the best way to fix it but at least it works
